!!python/object/apply:collections.OrderedDict
- - - buffer_size
    - 50000
  - - exploration_final_eps
    - 0.1
  - - exploration_fraction
    - 0.1
  - - learning_rate
    - 0.001
  - - n_timesteps
    - 100000
  - - param_noise
    - true
  - - policy
    - CustomDQNPolicy
